name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t yoka24/my-python-app:latest .

      - name: Push Docker image
        run: docker push yoka24/my-python-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deployment
        run: echo "Deploying to staging server..."
  steps:
      - name: Симуляція деплою на staging
        run: echo "Deploying my-python-app to staging server..."
